# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefillTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_count', models.IntegerField(default=0)),
                ('prescription_id', models.IntegerField()),
                ('created_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
