# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_remove_refilltracker_prescription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='refilltracker',
            name='prescription_id',
            field=models.IntegerField(default=0),
        ),
    ]
