# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drchronoauth',
            name='token',
        ),
        migrations.AddField(
            model_name='drchronoauth',
            name='access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drchronoauth',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drchronoauth',
            name='token_expiration',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
